version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: symfommerce
      POSTGRES_PASSWORD: symfommerce_123
      POSTGRES_DB: symfommerce
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@symfommerce.com
      PGADMIN_DEFAULT_PASSWORD: symfommerce_123
    ports:
      - "8080:80"
    depends_on:
      - db
